CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    user_id BIGSERIAL NOT NULL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    telephone VARCHAR(255) UNIQUE NOT NULL,
    profession VARCHAR(255) NOT NULL,
    number_of_id_card VARCHAR(255) UNIQUE NOT NULL,
    purpose_of_research VARCHAR(255) NOT NULL,
    join_date DATE NOT NULL,
    role VARCHAR(255) NOT NULL
);